---

- name: install git 
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
   - java-1.8.0-openjdk-devel.x86_64

- name: download scalla
  shell: >
    #wget http://www.scala-lang.org/files/archive/scala-2.10.3.tgz -O scala-2.10.3.tar.gz
    wget http://www.scala-lang.org/files/archive/scala-2.10.3.rpm -O scala-2.10.3.rpm


- name: config kafka
  shell: >
    #tar -xvzf scala-2.10.3.tar.gz;
    #mv scala-2.10.3 /usr/lib;
    #ln -s /usr/lib/scala-2.10.3 /usr/lib/scala
    rpm -ivh scala-2.10.3.rpm

- unarchive: 
    src: http://www.us.apache.org/dist/kafka/0.10.0.1/kafka_2.10-0.10.0.1.tgz 
    dest: /usr/share/kafka
    remote_src: True

- name: Remove Ip Rules
  shell: >
   iptables -D INPUT -p tcp --dport 3888 -j ACCEPT;
   iptables -D INPUT -p tcp --dport 2888 -j ACCEPT;
   iptables -D INPUT -p tcp --dport 2181 -j ACCEPT;
  ignore_errors: yes

- name: Setup Ip tables
  shell: >
    iptables -I INPUT -p tcp --dport 3888 -j ACCEPT;
    iptables -I INPUT -p tcp --dport 2888 -j ACCEPT;
    iptables -I INPUT -p tcp --dport 2181 -j ACCEPT;
  
- name: save iptables
  command: iptables-save

  
